/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference path="./.next/types/routes.d.ts" />
// pls dont chnage this file it is auto generated by nextjs and will be overwritten when nextjs updates